pull_request_rules:
  - name: automatic merge for Depfu pull requests
    conditions:
      - author=depfu[bot]
    actions:
      merge:
        method: merge

  - name: automatic merge for ImgBot pull requests
    conditions:
      - author=imgbot[bot]
    actions:
      merge:
        method: merge